== Complots divers

Source: https://www.univers-jdr.com/intrigues-et-complots-20-idees-a-developper/

1. Faire la lumière sur une disparition mystérieuse en veillant à ne pas attirer l'attention.
2. Découvrir d'où vient une faille de sécurité suite à des informations sensibles retrouvées entre des mains extérieures.
3. Gérer une crise diplomatique entre deux (ou plus) factions alors que leurs enfants s'aiment.
4. Choisir un camp dans un complot en cours pour prendre le pouvoir.
5. Explorer une partie d'un monument nouvellement découvert suite à des travaux.
6. Laver son honneur suite à d'odieuses accusations de crimes.
7. Empêcher la vengeance d'un individu à qui un protagoniste a fait du tord par le passé.
8. Faire la lumière sur l'incarcération d'un individu qui clame son innocence.
9. Enquêter sur des crimes ignobles perpétrés en interprétant des préceptes religieux.
10. Collaborer avec un tueur pour en attraper un autre.
11. Enquêter sur un crime surnaturel qui a conduit à la mort d'un éminente personne. Vrai surnaturel ou mise en scène?
12. Capturer un tueur en série qui sévit en ville. Après enquête, les protagonistes découvrent qu'il s'agit de l'un d'entre eux! Folie, manipulation ou malédiction?
13. Empêcher une organisation de mettre la main sur a formule d'un nouveau produit qui accroît les capacités d'un individu, avec ou sans effets secondaires.
14. Capturer ou éliminer un montre qui sévit dans la ville ou ailleurs.
15. Protéger une personne qui a reçu des menaces de mort.
16. Comprendre pourquoi une personne est vue plusieurs fois dans différents endroits à la même heure.
17. Espionner ou saboter une organisation ennemie.
18. S'échapper d'un lieu dans lequel les protagonistes sont enfermés.
19. Survivre à une catastrophe naturelle.
20. Cambrioler un lieu hautement sécurisé pour récupérer un objet.
