== Liste d'intrigues

Référence https://fudge.ouvaton.org/GrandeListe.html

Voici la traduction de la traduction de l'article de S. John Ross.

On peut utiliser les intrigues:

- dans la préparation de l'histoire
- en cours de partie si on veut créer une "quête secondaire"
- lors du climax si l'on veut créer une ouverture vers le prochain épisode

Evidemment on peut mixer les intrigues entre elles.

== Généralités

*Utilisez les métaphores*

John Ross a écrit ces intrigues dans un langage orienté vers un genre aventure-action, parce que c'est là la forme la plus courante des scénarios de jeu de rôle. Mais si vous avez l'habitude de jouer un autre style, vous pouvez quand même utiliser cette liste. Il vous suffit de remplacer un objet par une information, un endroit par une personne, un ennemi par un sentiment négatif, de même qu'une station spatiale peut être un donjon et un résidu magique une empreinte digitale.

*Double Couche*

Un principe de base intéressant est le jeu caméléon, où une aventure semble être d'un certain genre mais se révèle être autre chose. Parfois le passage de l'un à l'autre est innocent est naturel - Survie, par exemple, peut servir d'introduction à La Zone, et Étrange est une introduction logique à Portail. Parfois le passage est plus sinistre ou délibéré, avec des PNJs qui vendent une mission d'un type alors qu'on comprend ensuite qu'il se passe autre chose. Cela peut tout de même être innocent, si les PNJs se sont trompés, ou s'ils avaient désespérément besoin d'aide et craignait que personne ne vienne résoudre leur véritable problème.

*Expérimentez*

Choisissez deux intrigues au hasard, et imaginez une aventure avec elles, tout naturellement - la première servant d'introduction, la seconde de plat principal. Si la même intrigue sort deux fois, allez-y quand même ! Deux couches peuvent avoir une structure similaire mais des racines et des détails très différents.

*Double Couche, deuxième acte*

Une autre catégorie très intéressante de scénarios est l'enchevêtrement de deux intrigues séparées. Il est aisé par exemple de faire de l'une des intrigues l'intrigue physique et de l'autre l'intrigue personnelle. Ainsi seulement l'une des intrigues influence le lieu de l'action, tandis que l'autre peut avoir lieu n'importe où. Par exemple: les Héros sont engagés pour escorter un prince à un sommet pour qu'il puisse apparaître devant le peuple et mettre fin à une guerre (un exemple simple et physique d'Escorte), mais en chemin ils réalisent que le gars a des tendances suicidaires car les obligations de sa charge ont ruiné son histoire d'amour, et ils doivent l'empêcher de mettre fin à ses jours soit en arrangeant ses histoires, soit en le convaincant de passer à autre chose (un exemple personnel et métaphorique du Grain de Sable).

*Pas de Panique*

Beaucoup de MJs arrivent à la Grande Liste en état de panique scénaristique. Ne croyez pas que l'intrigue fait tout le scénario, comme beaucoup de MJs. Les intrigues présentées ici vous fournissent une structure simple et éprouvée, mais les intrigues ne servent réellement qu'à structurer une session. N'oubliez pas que l'essentiel du Jeu de Rôle c'est le Rôle, pas l'intrigue. Tout scénario qui contient une structure trop complexe éloignera l'attention du Rôle. Pour jouer il vous faut juste une structure basique, et savoir se laisser aller à l'inspiration du moment.

== La Grande Liste des 34 intrigues

|===
| Numéro  | Nom | Carte
| 1 | Amnésie | 7 Carreau ♢
| 2 | Base cachée | 8 Carreau ♢
| 3 | Capturer le drapeau | 9 Carreau ♢
| 4 | Chantage | 10 Carreau ♢
| 5 | Chasse à l’homme | Valet Carreau ♢
| 6 | Concours | Reine Carreau ♢
| 7 | Course au trésor | Roi Carreau ♢
| 8 | Défense: ils ne passeront pas | As Carreau ♢
| 9 | Déplacement: on est où là?  | 7 Trèfle ♣
| 10 | Détournement | 8 ♣ Trèfle
| 11 | Diplomatie: les bonnes manières  | 9 Trèfle ♣
| 12 | Effraction | 10 Trèfle ♣
| 13 | Enquête: élémentaire, mon cher Watson | Valet Trèfle ♣
| 14 | Escorte | Reine Trèfle ♣
| 15 | Étrange: comme c’est bizarre | Roi Trèfle ♣
| 16 | Exploration | As Trèfle ♣
| 17 | Fauteurs de trouble  | 7 Pique ♤
| 18 | Gestion (au travail) | 8 Pique ♤
| 19 | Grain de sable  | 9 Pique ♤
| 20 | Harcèlement: qu’est-ce qui se passe? | 10 Pique ♤
| 21 | Nettoyer la zone | Valet Pique ♤
| 22 | Portail: la boîte de Pandore | Reine Pique ♤
| 23 | Pourchasser: rattrapez-le!  | Roi Pique ♤
| 24 | Prison | As Pique ♤
| 25 | Quête  | 7 Coeur ♥
| 26 | Refuge: un abri dans la tempête | 8 Coeur ♥
| 27 | Ruines récentes  | 9 Coeur ♥
| 28 | Safari | 10 Coeur ♥
| 29 | Secours: ils sont en chemin  | Valet Coeur ♥
| 30 | Surveillance: ne pas toucher  | Reine Coeur ♥
| 31 | Survie: ne mangez pas les mauves   | Roi Coeur ♥
| 32 | Trésor | As Coeur ♥
| 33 | La Zone | Joker Rouge 🃟
| 34 | De l’autre côté de la barrière | Joker Noir 🂿
|===

=== Amnésie
Un Héros ou plus se réveillent sans souvenirs récents, et se retrouvent au cœur d'un problème qu'ils ne comprennent pas. Ils doivent trouver la raison de cette amnésie, et résoudre les problèmes.

[.underline]#Variations#

* Les Héros se sont rendus amnésiques volontairement, et essayent de comprendre leur propre travail
Base Cachée
Les Héros, au cours d'un voyage ou d'une exploration, tombent sur un nid de Méchant qui préparent un Truc Méchant. Ils doivent relayer l'information aux Gentils, ou s'infiltrer et démanteler l'opération eux-mêmes, ou une combinaison des deux.
Variations
* Les Héros doivent comprendre comment utiliser des ressources locales pour se défendre ou avoir une chance contre les habitants.

=== Capturer le Drapeau
Les Héros doivent s'emparer d'un objectif militaire. Les Méchants du coin s'y opposent.
Le scénario tactique habituel.

[.underline]#Variations#

* Les Héros doivent rassembler et/ou entraîner une force pour les aider.
* Les Héros ont de fausses informations et l'objectif ou son environnement immédiat ne sont pas comme ils s'y attendaient.
* Les Héros et un groupe allié doivent unir leurs efforts (parfois en mettant leurs rivalités de côté)
* La zone de l'objectif comporte une population innocente, des Machins fragiles, ou des trucs précieux qui ne doivent pas être pris entre deux feux

=== Chantage
Un Méchant a obtenu une information (illégalement, ou simplement en recherchant dans le passé des Héros) lui permettant de faire du chantage aux Héros. La menace peut être de tout type (physique, sociale, etc.) mais elle dépend du fait que le Méchant est en possession de quelque chose (objet ou information) que d'autres n'ont pas. Maintenant il tire les ficelles et ordonne aux Héros de faire des choses qu'ils ne veulent pas faire. Les Héros doivent mettre fin à ce chantage, lui ôter son avantage, tout en suivant ses instructions et en endormant sa méfiance.

[.underline]#Variations#

* En introduction de l'aventure, les Héros rendent un service au Méchant, qui l'utilise alors contre eux (très cynique!)
* Pour réussir, les Héros doivent contacter d'autres personnes victimes du même chantage.
* Les Héros ne sont pas directement victime du chantage, mais une personne qui est important à leurs yeux ou dont ils ont la charge l'est.

=== Chasse à l'Homme
Quelqu'un est parti: échappé, perdu, ou disparu. Quelqu'un a besoin de le retrouver. Les Héros sont appelés pour le retrouver et le ramener.

[.underline]#Variations#

* L'objectif a été kidnappé (peut-être pour attirer les Héros).
* L'objectif est dangereux et s'est échappé d'une prison.
* L'objectif est précieux et s'est échappé d'un endroit sûr, confortable et surveillé
* L'objectif s'est empêtré dans une autre aventure (comme protagoniste ou comme victime) et les Héros doivent le suivre pour l'en dépêtrer.
* L'objectif est un groupe en expédition ou en pèlerinage
* L'objectif ne s'est pas échappé/perdu, les Héros ont juste été engagés (peut-être sous de faux prétextes) pour le retrouver.

=== Concours
Les Héros participent à une course, un concours, un tournoi, une chasse ou un autre sport. Ils doivent gagner.

[.underline]#Variations#

* Les autres participants sont malhonnêtes et les Héros doivent les empêcher de gagner malhonnêtement
* Les Héros ont un autre objectif que la victoire, comme protéger un autre concurrent, ou l'espionner, ou juste accéder à un endroit où passe la course.
* Les Héros n'ont pas à gagner eux-mêmes; ils doivent juste empêcher le Méchant de gagner.
* L'évènement est une test délibéré des aptitudes des Héros (pour les faire entrer dans une organisation par exemple).
* L'évènement devient plus mortel que ce qu'il était supposé être.

=== Course au Trésor
Il y a à un endroit précis un Machin important et précieux. Les Héros (ou leurs employeurs) veulent s'en emparer, mais d'autres groupes également. Pour avoir une chance de réussir il faut être plus intelligent, plus rapide, utiliser au mieux les autochtones, être mieux renseigné sur l'objectif. Chaque groupe en compétition a son propre agenda et ses propres ressources.

[.underline]#Variations#

* Les autochtones demandent aux groupes en compétition de défendre publiquement leur point de vue.
* Le Machin était en déplacement lorsque son transporteur s'est écrasé ou a disparu

=== Défense (Ils ne passeront pas)
Les Héros doivent garder un endroit vital (un col de montagne, un système solaire...) contre toute attaque. Ils doivent planifier une stratégie de défense, effectuer des rondes, placer des pièges, etc. et ensuite faire face à l'ennemi lors de l'attaque.

[.underline]#Variations#

* Les renseignements initiaux sont faux, mais agir sur la base des nouveaux renseignements pourrait être plus dangereux encore - mais l'inaction également, et les Héros doivent choisir ou trouver un compromis
* Les Héros apprennent que l'ennemi a une bonne raison de détruire ou de s'emparer de l'endroit vital, et les Héros peuvent y être sensible.

=== Déplacement (On est où là ?)
Les Héros se retrouvent transporté à un endroit étrange. Ils doivent comprendre où ils se trouvent, comment ils sont arrivés là et pourquoi, et comment s'en échapper.

[.underline]#Variations#

* Les Héros ont été amené là pour aider quelqu'un en danger.
* Ils ont été amené là par accident, un effet secondaire de quelque chose d'étrange et de secret.
* Des ennemis des Héros ont été transportés avec les Héros (ou séparément), et ils se retrouvent sur un nouveau terrain de bataille, et parmi de nouveaux innocents qui ne savent pas qui sont les Gentils et les Méchants

=== Détournement
Les Héros sont à bord d'un moyen de transport plein de monde (Paquebot, Ferry, Vaisseau-Colonie) quand il fait l'objet d'un détournement. Les Héros doivent agir pendant que les autres passagers subissent.

[.underline]#Variations#

* Les "Pirates" sont des agents du gouvernement faisant partie d'une intrigue complexe, et les Héros doivent choisir leur camp
* Les pirates ne réalisent pas qu'il y a un autre danger, et toute tentative de les convaincre est prise pour un mensonge.
* Les autres passagers n'aident pas les Héros ou sont même hostiles car ils pensent que toute action ne fera qu'empirer les choses.

=== Diplomatie (Les Bonnes Manières)
Les Héros font partie d'une mission diplomatique qui cherche à ouvrir des relations politiques ou commerciales avec une étrange culture. Il leur suffit de ne pas faire de faux-pas et de n'offenser personne, mais ils ont des informations incomplètes ou fausses sur les coutumes du coin.

[.underline]#Variations#

* Les Héros ont été choisi par quelqu'un qui savait qu'ils n'étaient pas préparés - un PNJ qui essaie de saboter la mission (trouver le Méchant peut être nécessaire pour éviter un désastre)

=== Effraction
Objectif: entrer dans un endroit dangereux, démanteler les défenses du coin et s'emparer du Machin ou d'une personne importante.

[.underline]#Variations#

* Le but n'est pas de s'emparer d'un Machin, mais de le détruire, ou d'interrompre un processus (détruire le générateur de champ de force, assassiner le méchant roi, interrompre un rituel de lancement de sort, mettre par terre les plans d'invasions, refermer le portail)
* L'objectif a bougé.
* L'objectif est une information qui doit être diffusée dès qu'elle est trouvée.
* Le boulot doit être fait sans alerter personne.
* Les Héros ne savent pas que l'endroit est dangereux
* Les Héros doivent remplacer le Machin par un autre Machin

=== Enquête (Élémentaire, mon cher Watson)
Un crime ou une atrocité ont été commis. Les Héros doivent résoudre l'affaire. Ils doivent interviewer les témoins (et empêcher qu'ils soient tués), rassembler des indices (et empêcher qu'ils soient volés ou effacés). Ils doivent ensuite rassembler des preuves à livrer aux autorités, ou faire eux-même justice.

Les héros devront trouver des pistes, les suivre. Ces pistes les amèneront vers d’autres pistes. Idéalement, il faudrait que le cheminement ne soit pas linéaire, c’est à dire, offrir plusieurs pistes ou des pistes ambiguës.

Une autre façon de procéder également est d’avoir plusieurs suspects potentiels et ne décider que bien plus tard qui est le vrai coupable en fonction du cheminement des Héros.

[.underline]#Variations#

* Les Héros doivent laver un innocent de tout soupçon (peut-être eux-mêmes)
* Les Héros doivent travailler de concert avec un enquêteur spécial, ou se retrouvent avec un allier indésirable.
* Au milieu de l'aventure, on leur enlève l'enquête (souvent suite à une manœuvre d'un antagoniste)
* La scène finale se déroule au tribunal
* L'échelle pour ce type d'aventure est très variable, du meurtre de bourgade au scandale de pollution à l'échelle planétaire.

=== Escorte
Les Héros escortent un Machin précieux (objet ou personne) qui doit faire un voyage pour atteindre un endroit sûr ou son propriétaire. Le voyage est dangereux, et une ou plusieurs factions (ou des mésaventures) essayent de leur soustraire le Machin.

[.underline]#Variations#

* Le Machin est une source de problème, et cherche à s'échapper ou à doubler les Héros
* La destination a été détruite ou prise par l'ennemi, et les Héros finir eux-même le travail que le Machin devait accomplir en arrivant là-bas.
* La personne essaye de changer de camp.
* L'arrivée à destination n'est pas la fin de l'histoire; Les Héros doivent négocier un échange entre leur Machin et un autre Machin (échanger des otages contre de l'argent par exemple).
* Les Héros doivent protéger le Machin sans que le Machin s'en aperçoive

=== Étrange (Comme c'est bizarre...)
Quelque chose de mauvais et d'inexplicable est en train de se produire (tension raciale, coupure de courant, plus de bière, neige en juillet, des hordes d'aliens mangent tout le fromage) et beaucoup de gens sont dérangés par cela. Ils Héros doivent remonter à la source du phénomène et y remédier.

[.underline]#Variations#

* Mes Héros sont responsables sans le savoir de la situation.
* Le problème est en fait d'une nature différence de sa nature apparente (technologique, personnelle, biologique, chimique, magique, politique, etc.).

=== Exploration
Les Héros sont des explorateurs, et leur objectif est d'entrer dans un territoire inconnu et de l'explorer. Bien-sûr il y a un danger fascinant quelque part.

[.underline]#Variations#

* L'endroit lui-même est la menace, et les Héros doivent remplir leur mission tout en restant en bonne santé, y compris mentale et financière.
* L'endroit est merveilleux et très précieux, et quelque chose d'autre essaye de faire en sorte que les Héros ne le fasse savoir à personne.
* Une menace qui endommage les transports ou les équipements de communication des Héros transforme cette intrigue en Survie

=== Fauteurs de Troubles
Un Méchant (ou un groupe de Méchant, ou plusieurs groupes) sème l'anarchie, dérangeant le voisinage, empoisonnant les réservoirs, etc. Les Héros doivent voir sur place, localiser le Méchant et l'arrêter.

[.underline]#Variations#

* Les Héros ne doivent pas blesser le Méchant, il doit être ramené vivant et en bonne santé
* Le Méchant a préparé quelque chose de dangereux et de caché au cas où il serait capturé
* Le Méchant est un monstre ou un animal dangereux (ou une créature intelligente que tout le monde prend pour un monstre ou un animal)
* Le Méchant est un personnage public respecté, un officier supérieur, ou quelqu'un qui abuse de son autorité, et les Héros pourraient être confronté à l'hostilité des locaux qui ne peuvent croire que le Méchant soit Méchant.
* Les troubles sont alimentés par un équilibre des pouvoirs, et les Héros doivent choisir leur camp pour faire pencher la balance d'un côté et remettre les choses dans l'ordre.
* Les troubles sont diplomatiques ou politiques, et les Héros doivent rétablir la paix, pas la guerre.

=== Gestion (Au travail!)
Les Héros sont mis à la tête d'une importante organisation (une entreprise, une baronnie féodale, la CIA) et doivent, malgré leur manque d'expérience en la matière, la faire fonctionner et prospérer

[.underline]#Variations#

* Les Héros ont été mis là parce que quelque chose d'important va arriver, et la Vieille Garde veut s'échapper
* Les paysans, voisins, employés, etc. en veulent aux Héros car la raison de leur arrivée à la tête semble étrange, et tout le monde aimait les anciens dirigeants.

=== Grain de Sable
Un Méchant ou une organisation prépare un truc méchant, et les Héros ont reçu un renseignement dessus. Ils doivent enquêter pour comprendre ce qui se passe et agir pour empêcher sa réalisation.

[.underline]#Variations#

* Le renseignement initial était en fait destiné à les lancer sur une fausse piste.
* Il y a deux trucs méchants en préparation, et pas moyen d'arrêter les deux en même temps - comment choisir ?

=== Harcèlement (Qu'est-ce qui se passe ?)
Les Héros sont soudainement attaqués ou menacés sans qu'ils comprennent pourquoi. Ils doivent comprendre les motifs des attaquants tout en repoussant leurs attaques. Ils doivent ensuite résoudre le problème.

[.underline]#Variations#

* Les Héros sont sans le savoir en possession d'un Machin que veulent les Méchants.
* Les Méchants cherchent à se venger de la mort d'un compatriote lors d'une aventure précédente.
* Les Méchants se sont trompés et ont pris les Héros pour quelqu'un d'autre.

=== Nettoyer la Zone
Il y a un endroit avec des Choses Méchantes. Les Héros doivent les éliminer systématiquement pour assurer la sécurité des Gentils.

[.underline]#Variations#

* Les Choses Méchantes ne peuvent pas être battues par une confrontation directe.
* Les Héros doivent d'abord en apprendre plus pour elles pour résoudre le problème.
* La Maison Hantée.
* L'Invasion Extra-Terrestre.
* La Forêt Sauvage.

=== Portail (La Boite de Pandore)
Quelqu'un a joué avec un Machin Auquel Il Ne Fallait Pas Toucher, ou ouvert un portail vers une Dimension Infernale, ou éventré le mur d'une prison, ou invoqué un Grand Ancien dans un bordel. Avant de se confronter à la source du problème, les Héros doivent s'occuper des vagues de problèmes échappés du Machin: monstres, anciens ennemis vengeurs, aliens étranges qui mangent tout ce qui passe, etc.

[.underline]#Variations#

* Il faut que les Héros rassemblent les problèmes échappés et les renvoient à leur origine avant la fin de l'aventure.
* Les Héros sont attirés par la Source et doivent résoudre des problèmes de l'autre côté avant de retourner dans leur dimension
* Un livre secret, un code, ou un autre truc rare est nécessaire pour colmater la brèche (peut-être simplement celui qui l'a ouvert)
* Intrigue cousine: le voyage dans le passé qui a modifié le présent

=== Pourchasser (Rattrapez-les !)
Des Méchants sont arrivés et ont fait des Méchantes Choses. Les Héros n'ont rien pu empêcher. Les Méchants ont réussit à s'échapper, et les Héros ont réussit à les prendre en chasse et doivent les rattraper avant qu'ils rejoignent leur repaire, leur pays d'origine, les lignes ennemies, etc.

[.underline]#Variations#

* Les Méchants se sont enfuit en utilisant un moyen de transport ou une route que les Héros connaissent mieux qu'eux.
* Les Méchants se cachent temporairement dans un endroit (souvent hostile aux Héros
* Si les Méchants franchissent la ligne d'arrivée (la frontière, le portail dimensionnel, etc.) on ne pourra pas les poursuivre au-delà

=== Prison
Les Héros sont emprisonnés, et doivent s'échapper, malgré les gardes, les dispositifs de sécurité, et l'isolation géographique.

[.underline]#Variations#

* Quelque chose s'est passé à l'extérieur et la surveillance est relâchée.
* Les Héros sont engagés pour "tester" la prison - ils ne sont pas des prisonniers normaux.
* D'autres prisonniers décident d'avertir les gardes par dépit ou par vengeance
* Les Héros espionnent un autre prisonnier, mais on les prend pour de vrais prisonniers et ils sont incarcérés.
* Les Héros doivent faire vite pour rejoindre une autre aventure à l'extérieur.

=== Quête
Quelqu'un a besoin d'un Machin (pour compléter la prophétie, soigner le roi, empêcher la guerre, soigner une maladie, etc.). Les Héros doivent trouver le Machin. C'est souvent un Machin vieux, mystérieux, et puissant. Les Héros doivent en apprendre plus dessus pour le trouver, puis doivent s'en emparer.

[.underline]#Variations#

* Le Machin est incomplet lorsqu'il est trouvé (l'une des intrigues les plus irritantes et pas-drôle de tout l'univers).
* Quelqu'un possède le Machin (ou l'a volé récemment, parfois pour une raison ou une cause légitime).
* Le Machin est une information, ou une idée, ou une substance, pas un objet spécifique.
* Les Héros doivent infiltrer un groupe ou une société, et s'emparer du Machin discrètement

=== Refuge (Un Abri dans la Tempête)
Les Héros cherche un abri pour se protéger des éléments ou d'une autre menace, et trouvent un endroit où se réfugier. Ils découvrent qu'ils sont tombés sur quelque chose de dangereux, de secret, ou de surnaturel, et doivent résoudre le problème pour pouvoir enfin se reposer.

[.underline]#Variations#

* L'abri abrite également la source de la menace que les Héros cherchaient à éviter.
* L'abri est une Base Cachée (voir ce terme).
* Les Héros doivent lutter non seulement pour s'abriter, mais aussi pour survivre.
* L'abri est un abri légitime, mais les Héros ne sont pas les bienvenus, et doivent conquérir les cœurs ou les esprits pour être acceptés

=== Ruines Récentes
Une ville, château, vaisseau, campement, ou autre construction civilisée est en ruine. Alors qu'elle était en bon état encore récemment. Les Héros doivent entrer dans les ruines, les explorer, et découvrir ce qui s'est passé.

[.underline]#Variations#

* Ce qui a détruit l'endroit (Méchants, radiations, monstres, race inconnue, fantômes) est toujours une menace; Les Héros doivent l'éliminer.
* La "Ruine" est un vaisseau abandonné récemment découvert.
* La "Ruine" est une ville fantôme découverte au détour du chemin - mais la carte dit que c'est une ville normale.

=== Safari
Les Héros sont en expédition de chasse, pour capturer ou tuer une créature. Les problèmes sont liés à l'environnement, l'aptitude de la créature à leur échapper, et peut-être à les combattre.

[.underline]#Variations#

* La créature est immunisée à leurs équipements ou à leurs armes
* D'autres personnes protègent activement la créature.
* L'antre de la créature propulse les Héros vers une autre aventure.

=== Secours (Ils sont en Chemin)
Une personne (communauté, nation, galaxie) est en danger et doit être secourue par les Héros. L'introduction peut simplement être un appel au secours ou un signal de détresse.

[.underline]#Variations#

* La/Les Victime(s) est/sont retenue/s en otage, ou assiégée/s par l'ennemi, et les Héros doivent s'occuper des ravisseurs ou forcer le blocus.
* Il est possible que les secours se retrouvent dans la même situation que les personnes en détresse, multipliant le problème.
* Il faut secourir non pas des gens, mais des animaux, robots, ou autre chose
* La "victime" ne réalise pas qu'elle a besoin d'être secourue; elle se croit en sécurité
* La menace n'est pas liée à des Méchants mais à une catastrophe naturelle, nucléaire, ou une épidémie
* Les personnes en détresse ne peuvent pas bouger; il faut faire ou s'occuper de quelque chose sur place.
* Les Héros font partie des personnes en détresse au début de l'aventure, et doivent s'échapper pour rassembler des forces ou des ressources et secourir ceux qui sont restés sur place.

=== Surveillance (Ne Pas Toucher)
Les Héros font de la surveillance - espionner une personne, rassembler de l'information sur un animal sauvage, explorer un nouveau secteur. Quelle que soit l'échelle, il est impératif qu'ils ne soient pas repérés.

[.underline]#Variations#

* L'objectif a des problèmes et les Héros doivent décider qu'ils le secourent ou pas

=== Survie (Ne Mangez Pas Les Mauves)
Les Héros s'échouent dans un endroit bizarre, et doivent survivre en trouvant nourriture et abri, puis essayer de regagner leur maison.

[.underline]#Variations#

* Les Héros doivent survivre le temps que de l'aide arrive, qu'un truc soit réparé, etc.
* Dans les scénarios Réparations, les Héros doivent parfois découvrir un truc dans le coin qui rendra permettra d'effectuer les réparations

=== Trésor !
Les Héros sont des chasseurs de trésor, qui ont entendu parler d'une ruine où il y aurait un trésor. Ils doivent l'explorer, s'occuper des trucs pas naturels du coin pour s'emparer du trésor et ressortir vivants. (NdT: voir également Course Au Trésor)

[.underline]#Variations#

* Le trésor lui-même est dangereux.
* Le trésor n'est pas situé dans une ruine, mais dans la nature, ou même caché dans un endroit civilisé.
* Le trésor appartient légitimement à quelqu'un d'autre.
* Le trésor a une volonté propre.

=== La Zone
Les Héros doivent traverser une zone dangereuse sans être tué, volé, humilié, contaminé, par ce qui s'y trouve. Les problèmes sont rarement d'une nature personnelle - c'est l'endroit lui-même qui est le Méchant de l'aventure.

[.underline]#Variations#

* L'endroit n'est en fait pas dangereux du tout, et les "dangers" sont en fait des tentatives de prises de communication vers les Héros.

=== De l'autre côté de la barrière
Toutes les intrigues peuvent être transformées en mettant les Héros à l'extérieur. Soit les Héros accompagnent des PNJs au milieu de l'intrigue (et ils n'y entraînent pas les Héros qui doivent juste les défendre), ou les Héros assistent à une intrigue impliquant des PNJs et ils doivent choisir leur camp ou résister. Par exemple, avec "Refuge-Un Abri Dans La Tempête", les Héros pourraient être dans le refuge lorsqu'un autre groupe arrive; dans la variante "Les Héros ne sont pas les bienvenus", les Héros pourraient être la voix de la raison pour faire taire une ferveur religieuse, des préjugés raciaux, ou toute autre source de conflit.

[.underline]#Variations#

* Les Héros se trouvent dans le rôle des PNJs (les Méchants, les Fugitifs, etc.): au lieu de pourchasser, ils sont les Pourchassés; au lieu d'éliminer, ils doivent ne pas être éliminés.
* Ne pas toucher à l'intrigue de base, mais inverser les variations.

== Variantes génériques

La Petite Liste des Variantes Qui Fonctionnent Avec Presque Toutes Les Intrigues

* Les Héros doivent collaborer avec un PNJ ou une organisation qu'ils préfèrent éviter en temps normal (des rivaux, des Méchants, ou juste un expert insupportable envoyé pour les "aider").
* Les Victimes sont en fait les Méchants et inversement.
* Les Héros rencontrent des PNJs qui acceptent de les aider à condition qu'eux-mêmes les aident pour leur propre cause.
* Le Méchant est quelqu'un que les Héros connaissent personnellement, voire respectent ou aiment (ou quelqu'un qu'ils rencontrent en cours de route et trouvent sympathique).
* Les Héros doivent réussir sans violence, ou avec une discrétion particulière.
* Les Héros doivent réussir sans utiliser les pouvoirs, équipements ou autres ressources auxquels ils ont habituellement accès.
* Le Méchant est un méchant récurrent
* Un autre groupe comparable aux Héros a déjà raté la mission, et leurs corps/équipements/etc. fournissent aux Héros des indices pour faire mieux.
* Il y a des innocents aux alentours que les Héros doivent protéger tout en progressant.
* L'aventure commence brutalement sans introduction, les Héros sont directement au cœur de l'action.
* Les Héros doivent se faire passer pour d'autres, ou bien faire semblant d'avoir des allégeances, des valeurs ou des goûts différents.
* Les Héros ne peuvent pas tout faire et doivent choisir: quel Mal arrêter ? Quels innocents secourir ? Quelle valeur ou idéal promouvoir ?
* Les Héros doivent être un sacrifice personnel ou d'autres souffriront.
* Les Héros ne doivent pas résoudre le problème, mais aider avec le problème en toile de fond: faire passer une cargaison de vivres, faire sortir un patient qui a besoin d'aide médicale, etc.
* Un des Héros est (ou est présumé être) un héritier perdu, la réalisation d'une prophétie, un dieu du volcan, ou un sauveur quelconque, et est la raison pour laquelle les Héros sont embarqués dans l'aventure.
* Un autre groupe comparable aux Héros est en compétition avec eux sur la même aventure, peut-être avec des objectifs très différents.
* Il y a un compte-rebours qui pousse les Héros à agir vite et bien.
* Les Héros peuvent avoir des objectifs contradictoires secrets.